### PR TITLE
Improve GH actions

### PR DESCRIPTION
**Pull request by KTibow**
This combines HACS and hassfest into one file, and also adds some flake8 lint.

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. I don't think we're flake8 linted. Did you check to see that yet?

**Comment by KTibow** [comment]
I did check that. It also installs WPS (wemake-python-styleguide), to give you some recommendations for ideal code.

**Comment by alandtse** [comment]
Do you mind setting the extra flake tests as optional so we don't kill the build process until I've had a chance to review/fix?

**Comment by KTibow** [comment]
What do you mean? It always passes.

**Comment by alandtse** [comment]
I hadn't confirmed that the new action didn't fail you if it had warnings. Since it looks like it doesn't do that from your forks runs, I'll go ahead and merge it in.

**Pull request merged**
