### PR TITLE
fix: discovery not working

### LINKED ISSUE #697: Fails at start with TypeError: __init__() missing 1 required positional argument: 'request_refresh_debouncer'
**Describe the bug**
After an apparent succesfull 2FA, I get this error upon restart:
```
2020-05-09 21:58:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XXXXX@gmail.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/alexa_media/__init__.py", line 221, in async_setup_entry
    if await test_login_status(hass, config_entry, login, setup_alexa):
  File "/config/custom_components/alexa_media/configurator.py", line 180, in test_login_status
    await hass.async_add_job(alexa_setup_callback, hass, config_entry, login)
  File "/config/custom_components/alexa_media/__init__.py", line 880, in setup_alexa
    seconds=scan_interval * 10 if websocket_enabled else scan_interval
TypeError: __init__() missing 1 required positional argument: 'request_refresh_debouncer'
```

**To Reproduce**
1. Just restart

**System details**
 - Home-assistant (version): `0.105.4`
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): `v2.7.0`
 - alexapy (version from `pip show alexapy` or HA startup): `1.8.2`

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

### PR DESCRIPTION
**Pull request by paoloantinori**
fixes #697 

This is the error that I get during the init phase that prevents to discover my Alexa devices.

```
Sun May 10 2020 17:06:47 GMT+0200 (Central European Summer Time)
Error setting up entry paolo.antinori@gmail.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/alexa_media/__init__.py", line 221, in async_setup_entry
    if await test_login_status(hass, config_entry, login, setup_alexa):
  File "/config/custom_components/alexa_media/configurator.py", line 180, in test_login_status
    await hass.async_add_job(alexa_setup_callback, hass, config_entry, login)
  File "/config/custom_components/alexa_media/__init__.py", line 880, in setup_alexa
    seconds=scan_interval * 10 if websocket_enabled else scan_interval
TypeError: __init__() missing 1 required positional argument: 'request_refresh_debouncer'
Connection lost. Reconnecting…
```

This PR fixes the problem and allows me to find my devices.

I'm getting this on `Home Assistant 0.105.4`

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. What version of alex_media are you running? The version using with the Data Coordinator doesn't support versions less than HA 106 because 106 is where the Data Coordinator was added.

**Comment by alandtse** [comment]
Ok, this does break later versions. If you're able to fix it so it doesn't, then I can merge it in.

```
 2020-05-10 17:06:53 DEBUG (MainThread) [custom_components.alexa_media] Creating coordinator
 2020-05-10 17:06:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry alandtse@gmail.com - amazon.com for alexa_media
 Traceback (most recent call last):
   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
     hass, self
   File "/config/custom_components/alexa_media/__init__.py", line 222, in async_setup_entry
     if await test_login_status(hass, config_entry, login, setup_alexa):
   File "/config/custom_components/alexa_media/configurator.py", line 180, in test_login_status
     await hass.async_add_job(alexa_setup_callback, hass, config_entry, login)
   File "/config/custom_components/alexa_media/__init__.py", line 887, in setup_alexa
     True,
 TypeError: __init__() takes 3 positional arguments but 5 were given
```

**Comment by paoloantinori** [comment]
I'll try to work on this. Recent version of Home Assistant fai on my system, so it will slow down operations.

**Comment by alandtse** [comment]
I'll close this off as stale since we're now a few releases past this.

**Pull request closed without merging**
