### PR TITLE
Change sensor updating trigger to PUSH_ACTIVITY

### PR DESCRIPTION
**Pull request by francescolf**
Amazon stopped sending `NOTIFICATION_UPDATE` messages (at least for specific accounts, discussion in #1971)

This PR also adds a small delay in order to get updated data from the API.
These changes are proposed to the following accounts:
- amazon.it
- amazon.de
- amazon.com.au

The only current limitation is that Alexa commands must be sent ~10 seconds apart in order to update the sensors, but feedback is greatly appreciated.

### CODE REVIEW

**Comment by francescolf** [comment]
I replaced the command required to update the sensors since everyone should get _at least_ one `PUSH_ACTIVITY` message. However, for certain requests `PUSH_ACTIVITY` is received twice, triggering a useless double request which is now ignored.

**Comment by alandtse** [comment]
Thanks. I think you could've left the legacy code in. Amazon sometimes reverts changes and even if it's not used now, it could be useful.

**Comment by francescolf** [comment]
I'd prefer to keep it as is for two reasons:
1. The path for the serial number is different based on the message, resulting in more logic that increases latency
2. This solution triggers the update even if notification_update is supported since all the accounts receive push_activity messages

**Comment by alandtse** [comment]
People don't really test so it's not something we have historically relied on. Your edits shouldn't break anything and solves broken behavior so I'll just push a release and people can roll back if there is an issue. Thanks!

**Comment by dpgh947** [comment]
I just installed 4.6.5, doesn't work, timers still not updating. I would put this in the original issue but it's closed...

**Comment by amaisano** [comment]
Timers going from <not set> to <timer> instantly get picked up. HOWEVER:

- Snooze events no longer update the time sensor
- Stopping a timer no longer changes the "Status" attribute from ON to OFF (it just stays on until HA restarts)

@alandtse

**Comment by alandtse** [comment]
Don't tag people. It's rude. Amazon removed this feature. The fix is a stop gap but can only trigger on voice events. Any non voice interactions will not be picked up anymore.

**Comment by amaisano** [comment]
Apologies.

The thing is, "Alexa, snooze timer" and "Alexa, stop time" are both "voice events," right? So I should expect those events to keep working... or am I misunderstanding something?

**Comment by jane-t** [comment]
Any chance you could add the fix for the UK as well.  My timers are not working, or at least they feed in correctly when started but do no go away when stopped.

**Review by Randyblo7 — APPROVED** [review]

**Comment by oneseventhree** [comment]
> Don't tag people. It's rude. Amazon removed this feature. The fix is a stop gap but can only trigger on voice events. Any non voice interactions will not be picked up anymore.

how an we go about doing this?

**Pull request merged**
