### PR TITLE
feat: add last_called notify service target

### LINKED ISSUE #1104: Is a new service: notify.alexa_media_last_alexa possible?
This would be nice rather than having to code a templated entity...
```
service: media_player.play_media
data:
  entity_id: '{{ states.sensor.last_alexa.state }}'
  media_content_id: Alexa.GoodMorning.Play
  media_content_type: sequence
```

### PR DESCRIPTION
**Pull request by alandtse**
This requires HA to allow dynamic targets.
closes #1104

### CODE REVIEW

**Comment by cibernox** [comment]
@alandtse In what version of HA are dynamic targets added? Does this require any user configuration?

**Comment by alandtse** [comment]
It's automatic. It works without dynamic targets although it's less efficient. Once HA allows it, it'll switch over to the more efficient version.

**Comment by alandtse** [comment]
As a note, until HA's release next month, there is a 4 second delay for the notify target to fully update.

**Comment by cibernox** [comment]
Thanks for the heads up. 

Is that 4s any worse than the time taken by the current workaround of defining a custom sensor in home assistant?

**Pull request merged**
