### PR TITLE
fix: detect ledvance bluetooth bulbs #1839

### PR DESCRIPTION
**Pull request by Lippiero**
Draft for a change which let alexa media player detect local ledvance bulbs #1839

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Isn't this a new feature? We never supported these lights before.

**Comment by Lippiero** [comment]
I wasn't sure... it seems to be a bit of both... on the one hand it is a fix because the existing code catches other lights as well on the other hand yes, you are also right, if you say, they were not supported before. Should I change something?

I don't know, why one of the checks failed. There is no real hint given in the output. Is it ok though?

**Comment by alandtse** [comment]
Don't worry about the pre-commit. For some reason it's not finding pylint.

**Review by Randyblo7 — APPROVED** [review]

**Review by Randyblo7 — COMMENTED** [review]
Nice

**Review by Randyblo7 — APPROVED** [review]

**Review by Randyblo7 — APPROVED** [review]

**Review by Randyblo7 — APPROVED** [review]

**Review by Randyblo7 — APPROVED** [review]

**Review by Randyblo7 — APPROVED** [review]

**Review by Randyblo7 — APPROVED** [review]

**Pull request merged**
