### PR TITLE
Fix cookie issues

### PR DESCRIPTION
**Pull request by quthla**
https://github.com/custom-components/alexa_media_player/issues/1512

I ran into this issue and this fixed it for me.

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Please also disable the UI option to switch to `Use Login Proxy method (2FA not required)` with an relogin attempt. Otherwise, that will be silently broken with this change.

**Comment by alandtse** [comment]
Oh let me explain. So yes, the login proxy method is preferred. However, the error in #1512 is caused when the login attempts to switch from the old legacy python based login to the proxy method. By removing the check you have done, you have disabled that conversion path, but the UI will end up in a loop because it won't be able to process that path despite the UI selection. 

You can recreate that effect by using the `force_logout` service, and then restarting HA. It will automatically try to relogin and if you then try to switch to login proxy, it should give you that error.

**Comment by quthla** [comment]
Which situations is the path meant for exactly? I'm aware I removed the lastreq stuff but as proxy method still worked, I figured the code might be superfluous after all.

**Comment by alandtse** [comment]
You could switch to proxy after any data entry screen to resume the login attempt. We need to remove any such switches where state was previously preserved. Or perhaps we don't make that guarantee and always restart.

**Comment by quthla** [comment]
I'd say let's leave it as it is now. The path was broken anyway which led to never being able to reauthenticate via proxy and that's fixed now.

**Comment by alandtse** [comment]
Ok you've convinced me. Thanks!

**Pull request merged**
